---
name: "Nix build"
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
jobs:
  build:
    name: ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    permissions:
      id-token: "write"
      contents: "read"
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-24.04, target: x86_64-linux }
          - { os: macos-14, target: aarch64-darwin }
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v10
    - uses: cachix/cachix-action@v12
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -L --accept-flake-config
    - run: |
        nix build .#rustowl
        nix build .#rustowl-nvim
